window._printTemplateData = {
  "version": 2,
  "layouts": {
    "1": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 200
        }
      ],
      "elements": [
        {
          "id": "e2",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 201.9,
          "h": 147.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 6.950000000000003,
          "y": 158.95000000000002,
          "w": 62.7,
          "h": 6.7,
          "fontSize": 16,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#666",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e4",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 62.5,
          "y": 154.5,
          "w": 64.3,
          "h": 15.6,
          "fontSize": 20,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 171.2,
          "w": 199.1,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e6",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 175.29999999999998,
          "w": 25.3,
          "h": 5,
          "fontSize": 8.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#484747",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e7",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 26.5,
          "y": 193.2,
          "w": 27.9,
          "h": 6.2,
          "fontSize": 10,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#545454",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e8",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 71.2,
          "y": 175.29999999999998,
          "w": 30.6,
          "h": 5,
          "fontSize": 8.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#5e5e5e",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e9",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 94.65,
          "y": 193.2,
          "w": 29.4,
          "h": 8,
          "fontSize": 10,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#5e5e5e",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 167,
          "y": 193.2,
          "w": 35.6,
          "h": 7.6,
          "fontSize": 16,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#474747",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e11",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 140,
          "y": 154.5,
          "w": 65,
          "h": 8.8,
          "fontSize": 12,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e43",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 5,
          "y": 183.6,
          "w": 19.3,
          "h": 14.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e44",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 71.2,
          "y": 183.6,
          "w": 19.9,
          "h": 15,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "2": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 138
        },
        {
          "x": 5,
          "y": 154,
          "w": 200,
          "h": 138
        }
      ],
      "elements": [
        {
          "id": "e12",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 5.8,
          "w": 126.6,
          "h": 105.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 139.2,
          "y": 8.399999999999999,
          "w": 65.8,
          "h": 8.5,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 137.7,
          "y": 18.7,
          "w": 66.7,
          "h": 11.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e16",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 137.7,
          "y": 40.099999999999994,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e17",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 138,
          "y": 46.099999999999994,
          "w": 67,
          "h": 4.4,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e18",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 137.7,
          "y": 77.2,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e19",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 137.7,
          "y": 81.60000000000001,
          "w": 67.3,
          "h": 9.2,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 9,
          "y": 113.5,
          "w": 120,
          "h": 7,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e22",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 135,
          "y": 117,
          "w": 66,
          "h": 12,
          "fontSize": 13,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e43",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 138.9,
          "y": 62.3,
          "w": 61.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e72",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 174.2,
          "y": 40.099999999999994,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e73",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 174.2,
          "y": 77.2,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e161",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 9,
          "y": 154.8,
          "w": 126.6,
          "h": 105.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e162",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 139.2,
          "y": 157.4,
          "w": 65.8,
          "h": 8.5,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e163",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 137.7,
          "y": 167.7,
          "w": 66.7,
          "h": 11.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e164",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 137.7,
          "y": 189.1,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e165",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 138,
          "y": 195.1,
          "w": 67,
          "h": 4.4,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e166",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 137.7,
          "y": 226.2,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e167",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 137.7,
          "y": 230.60000000000002,
          "w": 67.3,
          "h": 9.2,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e168",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 9,
          "y": 262.5,
          "w": 120,
          "h": 7,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e169",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 135,
          "y": 266,
          "w": 66,
          "h": 12,
          "fontSize": 13,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e170",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 138.9,
          "y": 211.3,
          "w": 61.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e171",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 174.2,
          "y": 189.1,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e172",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 174.2,
          "y": 226.2,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "3": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 88
        },
        {
          "x": 5,
          "y": 103,
          "w": 200,
          "h": 88
        },
        {
          "x": 5,
          "y": 201,
          "w": 200,
          "h": 88
        }
      ],
      "elements": [
        {
          "id": "e23",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5.3,
          "y": 7.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e25",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 120.2,
          "y": 9.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e26",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 119.8,
          "y": 19,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e27",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 119.5,
          "y": 34.6,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e28",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 119.5,
          "y": 40.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e29",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 120.2,
          "y": 60,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e30",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 120.2,
          "y": 66,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 118.8,
          "y": 52.8,
          "w": 82.9,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e32",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 9,
          "y": 81,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 135,
          "y": 77,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e44",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 149.5,
          "y": 34.6,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e45",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 149.5,
          "y": 60,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e124",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 5.3,
          "y": 105.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e125",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 120.2,
          "y": 107.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e126",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 119.8,
          "y": 117,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e127",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 119.5,
          "y": 132.6,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e128",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 119.5,
          "y": 138.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e129",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 120.2,
          "y": 158,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e130",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 120.2,
          "y": 164,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e131",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 118.8,
          "y": 150.8,
          "w": 82.9,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e132",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 9,
          "y": 179,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e133",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 135,
          "y": 175,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e134",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 149.5,
          "y": 132.6,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e135",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 149.5,
          "y": 158,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e136",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 5.3,
          "y": 203.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e137",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 120.2,
          "y": 205.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e138",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 119.8,
          "y": 215,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e139",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 119.5,
          "y": 230.6,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e140",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 119.5,
          "y": 236.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e141",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 120.2,
          "y": 256,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e142",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 120.2,
          "y": 262,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e143",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 118.8,
          "y": 248.8,
          "w": 82.9,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e144",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 9,
          "y": 277,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e145",
          "type": "field",
          "field": "price",
          "cardIndex": 2,
          "x": 135,
          "y": 273,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e146",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 149.5,
          "y": 230.6,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e147",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 149.5,
          "y": 256,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "4": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 97,
          "h": 138
        },
        {
          "x": 108,
          "y": 5,
          "w": 97,
          "h": 138
        },
        {
          "x": 5,
          "y": 154,
          "w": 97,
          "h": 138
        },
        {
          "x": 108,
          "y": 154,
          "w": 97,
          "h": 138
        }
      ],
      "elements": [
        {
          "id": "e34",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5.7,
          "y": 5,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e36",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 9,
          "y": 93.5,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 108,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e38",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 9,
          "y": 114,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 125,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 9,
          "y": 131,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 5,
          "y": 131,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e42",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 59.3,
          "y": 93.5,
          "w": 42.7,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e88",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 41.650000000000006,
          "y": 108,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e89",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 41.650000000000006,
          "y": 130,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e90",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 122.7,
          "w": 87.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e91",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 108.7,
          "y": 5,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e92",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 112,
          "y": 93.5,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e93",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112,
          "y": 108,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e94",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 112,
          "y": 114,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e95",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112,
          "y": 125,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e96",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 112,
          "y": 131,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e97",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 108,
          "y": 131,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e98",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 162.3,
          "y": 93.5,
          "w": 42.7,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e99",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 144.65,
          "y": 108,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e100",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 144.65,
          "y": 130,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e101",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 112,
          "y": 122.7,
          "w": 87.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e102",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 5.7,
          "y": 154,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e103",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 9,
          "y": 242.5,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e104",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 257,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e105",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 9,
          "y": 263,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e106",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 274,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e107",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 9,
          "y": 280,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e108",
          "type": "field",
          "field": "price",
          "cardIndex": 2,
          "x": 5,
          "y": 280,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e109",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 59.3,
          "y": 242.5,
          "w": 42.7,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e110",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 41.650000000000006,
          "y": 257,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e111",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 41.650000000000006,
          "y": 279,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e112",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 271.7,
          "w": 87.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e113",
          "type": "image3d",
          "field": null,
          "cardIndex": 3,
          "x": 108.7,
          "y": 154,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e114",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 3,
          "x": 112,
          "y": 242.5,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e115",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 112,
          "y": 257,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e116",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 112,
          "y": 263,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e117",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 112,
          "y": 274,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e118",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 112,
          "y": 280,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e119",
          "type": "field",
          "field": "price",
          "cardIndex": 3,
          "x": 108,
          "y": 280,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e120",
          "type": "field",
          "field": "code",
          "cardIndex": 3,
          "x": 162.3,
          "y": 242.5,
          "w": 42.7,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e121",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 144.65,
          "y": 257,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e122",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 144.65,
          "y": 279,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e123",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 112,
          "y": 271.7,
          "w": 87.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        }
      ]
    }
  }
};
