window._printTemplateData = {
  "version": 2,
  "layouts": {
    "1": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 200
        }
      ],
      "elements": [
        {
          "id": "e2",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 133.4,
          "h": 154.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 103.8,
          "y": 6.8,
          "w": 62.7,
          "h": 6.7,
          "fontSize": 15,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#666",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e4",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 109.2,
          "y": 16.6,
          "w": 64.3,
          "h": 15.6,
          "fontSize": 17.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 141.2,
          "y": 55.4,
          "w": 62.4,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e6",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 141.2,
          "y": 33.1,
          "w": 25.3,
          "h": 5,
          "fontSize": 8.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e7",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 107.2,
          "y": 34.8,
          "w": 49.4,
          "h": 10.4,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e8",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 140.9,
          "y": 62.2,
          "w": 30.6,
          "h": 5,
          "fontSize": 8.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e9",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 141.4,
          "y": 68.6,
          "w": 29.4,
          "h": 8,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 137.7,
          "y": 89.6,
          "w": 65,
          "h": 14,
          "fontSize": 16,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e11",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 8.4,
          "y": 164.6,
          "w": 62.4,
          "h": 7,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e43",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 122.3,
          "y": 46.7,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e44",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 179.3,
          "y": 67.6,
          "w": 12,
          "h": 12,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "2": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 138
        },
        {
          "x": 5,
          "y": 154,
          "w": 200,
          "h": 138
        }
      ],
      "elements": [
        {
          "id": "e12",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 5.8,
          "w": 126.6,
          "h": 105.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 139.2,
          "y": 7.5,
          "w": 65.8,
          "h": 8.5,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 138,
          "y": 16.9,
          "w": 66.7,
          "h": 11.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e16",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 137.7,
          "y": 30.3,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e17",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 138,
          "y": 37.7,
          "w": 67,
          "h": 4.4,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e18",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 138,
          "y": 51.2,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e19",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 137.7,
          "y": 56.3,
          "w": 67.3,
          "h": 9.2,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 117,
          "w": 192,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 9,
          "y": 121,
          "w": 120,
          "h": 7,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e22",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 135,
          "y": 117,
          "w": 66,
          "h": 12,
          "fontSize": 13,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e43",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 138,
          "y": 46.3,
          "w": 65.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e44",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 9,
          "y": 154.8,
          "w": 126.6,
          "h": 105.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e45",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 139.2,
          "y": 156.5,
          "w": 65.8,
          "h": 8.5,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e46",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 138,
          "y": 165.9,
          "w": 66.7,
          "h": 11.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e47",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 137.7,
          "y": 179.3,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e48",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 138,
          "y": 186.7,
          "w": 67,
          "h": 4.4,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e49",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 138,
          "y": 200.2,
          "w": 50,
          "h": 6,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e50",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 137.7,
          "y": 205.3,
          "w": 67.3,
          "h": 9.2,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e51",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 9,
          "y": 266,
          "w": 192,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e52",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 9,
          "y": 270,
          "w": 120,
          "h": 7,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e53",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 135,
          "y": 266,
          "w": 66,
          "h": 12,
          "fontSize": 13,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e54",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 138,
          "y": 195.3,
          "w": 65.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        }
      ]
    },
    "3": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 88
        },
        {
          "x": 5,
          "y": 103,
          "w": 200,
          "h": 88
        },
        {
          "x": 5,
          "y": 201,
          "w": 200,
          "h": 88
        }
      ],
      "elements": [
        {
          "id": "e23",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5.3,
          "y": 7.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e25",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 120.2,
          "y": 9.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e26",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 121.4,
          "y": 17.2,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e27",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 119.8,
          "y": 30.8,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e28",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 119.8,
          "y": 35.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e29",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 119.5,
          "y": 48.4,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e30",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 119.5,
          "y": 53.2,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 77,
          "w": 192,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e32",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 9,
          "y": 81,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 135,
          "y": 77,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e55",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 5.3,
          "y": 105.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e56",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 120.2,
          "y": 107.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e57",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 121.4,
          "y": 115.2,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e58",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 119.8,
          "y": 128.8,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e59",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 119.8,
          "y": 133.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e60",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 119.5,
          "y": 146.4,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e61",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 119.5,
          "y": 151.2,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e62",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 9,
          "y": 175,
          "w": 192,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e63",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 9,
          "y": 179,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e64",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 135,
          "y": 175,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e65",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 5.3,
          "y": 203.4,
          "w": 105.8,
          "h": 69,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e66",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 120.2,
          "y": 205.2,
          "w": 70.3,
          "h": 6,
          "fontSize": 14.5,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#777",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e67",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 121.4,
          "y": 213.2,
          "w": 83.6,
          "h": 10.5,
          "fontSize": 19,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e68",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 119.8,
          "y": 226.8,
          "w": 32.4,
          "h": 3.8,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e69",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 119.8,
          "y": 231.6,
          "w": 34.4,
          "h": 7.3,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e70",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 119.5,
          "y": 244.4,
          "w": 50,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e71",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 119.5,
          "y": 249.2,
          "w": 60,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e72",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 273,
          "w": 192,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e73",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 9,
          "y": 277,
          "w": 120,
          "h": 6,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#888",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e74",
          "type": "field",
          "field": "price",
          "cardIndex": 2,
          "x": 135,
          "y": 273,
          "w": 66,
          "h": 10,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    },
    "4": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 97,
          "h": 138
        },
        {
          "x": 108,
          "y": 5,
          "w": 97,
          "h": 138
        },
        {
          "x": 5,
          "y": 154,
          "w": 97,
          "h": 138
        },
        {
          "x": 108,
          "y": 154,
          "w": 97,
          "h": 138
        }
      ],
      "elements": [
        {
          "id": "e34",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5.7,
          "y": 6,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e36",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 9,
          "y": 95,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 108,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e38",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 9,
          "y": 114,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9,
          "y": 125,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 9,
          "y": 131,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "field",
          "field": "price",
          "cardIndex": 0,
          "x": 5,
          "y": 128.9,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e42",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 7.5,
          "y": 137,
          "w": 89,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e102",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 108.7,
          "y": 6,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e103",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 112,
          "y": 95,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e104",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112,
          "y": 108,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e105",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 112,
          "y": 114,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e106",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112,
          "y": 125,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e107",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 112,
          "y": 131,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e108",
          "type": "field",
          "field": "price",
          "cardIndex": 1,
          "x": 108,
          "y": 128.9,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e109",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 110.5,
          "y": 137,
          "w": 89,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e110",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 5.7,
          "y": 155,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e111",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 9,
          "y": 244,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e112",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 257,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e113",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 9,
          "y": 263,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e114",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 9,
          "y": 274,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e115",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 9,
          "y": 280,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e116",
          "type": "field",
          "field": "price",
          "cardIndex": 2,
          "x": 5,
          "y": 277.9,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e117",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 7.5,
          "y": 286,
          "w": 89,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e118",
          "type": "image3d",
          "field": null,
          "cardIndex": 3,
          "x": 108.7,
          "y": 155,
          "w": 95.9,
          "h": 85,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e119",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 3,
          "x": 112,
          "y": 244,
          "w": 89,
          "h": 9,
          "fontSize": 14.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e120",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 112,
          "y": 257,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e121",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 112,
          "y": 263,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e122",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 112,
          "y": 274,
          "w": 44,
          "h": 5,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e123",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 112,
          "y": 280,
          "w": 89,
          "h": 7,
          "fontSize": 9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#333",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e124",
          "type": "field",
          "field": "price",
          "cardIndex": 3,
          "x": 108,
          "y": 277.9,
          "w": 89,
          "h": 11,
          "fontSize": 14,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e125",
          "type": "field",
          "field": "code",
          "cardIndex": 3,
          "x": 110.5,
          "y": 286,
          "w": 89,
          "h": 6,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "monospace",
          "color": "#999",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    }
  }
};
